name: Build and push to dockerhub

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Generate tag
        id: generate_tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"
      -
        name: Build and push
        run: |
          docker build -t joelralte/nodewebapi:${{ steps.generate_tag.outputs.tag }} .
          docker push joelralte/nodewebapi:${{ steps.generate_tag.outputs.tag }}
